### ISSUE TITLE
numpy2ri.converter issues AttributeError: __enter__

### ISSUE THREAD

**Issue by gjmoore** [rpy2/rpy2#1012]
Per the instructions provided in [https://github.com/rpy2/rpy2/blob/master/doc/numpy.rst](https://github.com/rpy2/rpy2/blob/master/doc/numpy.rst), using the numpy2ri.converter (`np_cv_rules = default_converter + numpy2ri.converter`) produces:

```
Traceback (most recent call last):
   File "rpy2bug_2.py", line 19, in <module>
     with np_cv_rules:
 AttributeError: __enter__
```
It's entirely possible this behaviour is due to "user error", so any assistance is much appreciated.

Simple example:

```
# for reference:
# $ python --version
# Python 3.9.16
# >>> rpy2.__version__
# '3.4.5'
# $ uname -rsv
# Darwin 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64

# rpy2 3.5.10 methodology:

import numpy as np
import rpy2.robjects as robjects
from rpy2.robjects import numpy2ri
from rpy2.robjects import default_converter

np_cv_rules = default_converter + numpy2ri.converter

with np_cv_rules:
    A_R = np.resize(np.arange(10),(2,5))

print(f'A_R is of type "{type(A_R)}"')
```

**Comment by lgautier** [comment]
The doc is does not reflect recent change (fixed with https://github.com/rpy2/rpy2/commit/912c6ed0f447075c5d551a8804d5e0fe6d998a1d).

This is a consequence of a bugfix in 3.5.10 (see https://rpy2.github.io/doc/latest/html/changes.html#id3).

Use the method `context`. See https://rpy2.github.io/doc/latest/html/robjects_environments.html#environments-as-temporary-local-contexts  .

**Comment by gjmoore** [comment]
Thank you!
