### ISSUE TITLE
How to install particular R packages when installing rpy2

### ISSUE THREAD

**Issue by MLopez-Ibanez** [rpy2/rpy2#1046]
**Is your feature request related to a problem? Please describe.**

I have a Python package (https://github.com/auto-optimization/iracepy) that wraps an R package. Currently, the user has to install R, then the R packages and then the python package.

**Describe the solution you'd like**

I would like some way to specify a list of R packages that need to be installed when rpy2 is installed.

**Describe alternatives you've considered**

I tried using rpy2 to install the packages: https://github.com/auto-optimization/iracepy/blob/main/install.py
but this doesn't work reliably. It is also unclear how to trigger this from 'pip install'

**Comment by lgautier** [comment]
Dependency management will be managed by the Python package installation system you are using. 

Otherwise the `rpy2` documentation outline how to install R package using `rpy2` (https://rpy2.github.io/doc/latest/html/robjects_rpackages.html#installing-removing-r-packages), however, there might be a few local variations to handle. For example, R version WRT to the availability of the R package version required, can/should the user install the R package in the main R library directory or in a local/user-specific directory. This is a R dependency management question.

Each language has its own set of solutions for dependency management. I believe that this is beyond the scope of `rpy2` itself. Reopen if I am missing something.
