### ISSUE TITLE
Problem installing  rpy2-3.5.14 

### ISSUE THREAD

**Issue by sharifamlani** [rpy2/rpy2#1064]
**Describe the issue or bug**

I'm trying to install rpy2 on my Windows machine using pip, but I've encountered an error that seems to be related to a missing file or command. Here's a summarized version of the error:

Command: pip install rpy2
Main Error: FileNotFoundError: [WinError 2] The system cannot find the file specified
Context:
The error occurred during the "Getting requirements to build wheel" phase.
It originates from a subprocess and might not be directly related to pip itself.
The traceback indicates an issue with a subprocess command in the rpy2 setup phase, specifically at the step where it tries to get R-related configurations.
Has anyone encountered a similar issue, or can provide some insights into resolving it?

**To Reproduce**
The error occurs when I run `pip install rpy2`

**Expected behavior**
Clean Installation

**Things I've tried**
Upgrading Python
Upgrading Anaconda
Uninstalling/Reinstalling Anaconda
Downloading the package manually from the https://pypi.org/project and running the installation manually
conda install -c conda-forge rpy2
Specifying R file location and R library location as an environmental variable in windows

**Error**
```Collecting rpy2
  Using cached rpy2-3.5.14.tar.gz (219 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      Traceback (most recent call last):
        File "C:\Users\amlanis\AppData\Local\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\amlanis\AppData\Local\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\amlanis\AppData\Local\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\amlanis\AppData\Local\Temp\pip-build-env-9t6j0vt4\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\amlanis\AppData\Local\Temp\pip-build-env-9t6j0vt4\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\amlanis\AppData\Local\Temp\pip-build-env-9t6j0vt4\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 137, in <module>
        File "<string>", line 109, in get_r_c_extension_status
        File "C:\Users\amlanis\AppData\Local\Temp\pip-install-v0f4lwsi\rpy2_7f053cb9fa2e45f89c012a61ba9040a8\./rpy2/situation.py", line 286, in get_r_flags
          _get_r_cmd_config(r_home, flags,
        File "C:\Users\amlanis\AppData\Local\Temp\pip-install-v0f4lwsi\rpy2_7f053cb9fa2e45f89c012a61ba9040a8\./rpy2/situation.py", line 246, in _get_r_cmd_config
          output = subprocess.check_output(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\amlanis\AppData\Local\anaconda3\Lib\subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\amlanis\AppData\Local\anaconda3\Lib\subprocess.py", line 548, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\amlanis\AppData\Local\anaconda3\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\amlanis\AppData\Local\anaconda3\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.```

**Comment by lgautier** [comment]
This happens here: https://github.com/rpy2/rpy2/blob/f8770064227b2ea5695d8627a4d1476f6d39361a/rpy2/situation.py#L246

I am guessing that R is not in your PATH. Can you start R from the terminal/console where you run `pip install rpy2` ? Can you try if `pip --verbose install rpy2` provides more information?

**Comment by gustavahlberg** [comment]
I have the exact same issue and I can most definitely open R in my terminal.

**Comment by pmdscully** [comment]
**I would verify that the `env` variables used by `R`** e.g. `path, R_HOME, R_LIBS_USER, R_USER` are set correctly.
e.g. (I have set as below, however you'll need to correct them for your R installation):
* `path`  - added:  `;X:\path\to\R\R-4.3.1\bin;X:\path\to\R\R-4.3.1;`
* `R_HOME` - set: `X:/path/to/R/R-4.3.1/`
* `R_LIBS_USER` -  `X:/path/to/R/R-4.3.1/library/` - although, I did not set

--- 
hacky notes (ymmv)

I had trouble with the `rpy2` installation. I resolved a similar error including `The system cannot find the file specified` printed to STDOUT (which indicates `env` variables might be missing) and a `CalledProcessError` exception due to non-zero exit code for a call of `Rcmd.exe config LIBnn` and later Python kernel crashes when importing some `rpy2` modules.

1. Within `situation.py->_get_r_cmd_config(..)`  (see [Line 246](https://github.com/rpy2/rpy2/blob/f8770064227b2ea5695d8627a4d1476f6d39361a/rpy2/situation.py#L246C10-L246C10)) , I wrapped the `CalledProcessError` exception within to extract the STDOUT output even on a non-zero exit code. (In my case, the error was post-installation when checking the installtion using `situation.py->iter_info()`. Here the STDOUT was `"lib"` with exit-code `1`).
```
    from subprocess import CalledProcessError
    try:
        output = subprocess.check_output(
            cmd,
            universal_newlines=True
        ).split(os.linesep)
    except CalledProcessError as e:
        output = e.output.split(os.linesep)
```
Note: I also added another hacky solution: *(I replaced `R CMD` with `RCMD`, i.e. calling `Rcmd.exe`)* [Line 244](https://github.com/rpy2/rpy2/blob/f8770064227b2ea5695d8627a4d1476f6d39361a/rpy2/situation.py#L244).
```
    #cmd = (r_exec, 'CMD', 'config', about)
    cmd = (r_exec+'CMD', 'config', about)
```

2. I noticed that the `R Installation` did not set the environment variables (`path, R_HOME, R_LIBS_USER, R_USER`), so (inspired by [a post-install kernel crash](https://stackoverflow.com/questions/58611486/r-kernel-crashes-while-loading-r-package-using-rpy2)) I reset these and restarted the terminal; this worked.

**Comment by lgautier** [comment]
@pmdscully - I don't have a Windows system to confirm it but my understanding is that `Rcmd` is long deprecated  (see https://stackoverflow.com/a/3415135/294017).

**Comment by lgautier** [comment]
With https://github.com/rpy2/rpy2/pull/1128 merged, building binaries in the API mode (the preferred mode) seems to be working. 

I uploaded binaries for Python 3.9 to 3.12 and the dev version of rpy2-3.6.0.  Building for Python 3.13 might work the same way but I have not tried yet.

To install for Python 3.9 to 3.12 the following should just work:
```
pip install -U --pre rpy2-rinterface rpy2-robjects
```

**Comment by lgautier** [comment]
The CI pipeline creates binary wheels for Windows. They can be fetch from a pipeline run. Otherwise I have upload dev version on Pypi. They can be installed with: 
```sh
pip install -U --pre rpy2
```
