### ISSUE TITLE
Add Arrow support

### ISSUE THREAD

**Issue by Wainberg** [rpy2/rpy2#1080]
rpy2-arrow is just 337 lines of code in https://github.com/rpy2/rpy2-arrow/blob/main/rpy2_arrow/arrow.py plus 49 in https://github.com/rpy2/rpy2-arrow/blob/main/rpy2_arrow/r6b.py. It would be trivial to support Arrow by either incorporating this code directly into rpy2, or writing similar code from scratch.

The reason I'm bringing this up is that a developer of [polars](https://github.com/pola-rs/polars), a popular (22,000 Github stars) DataFrame library built on Arrow, has expressed interest in integrating rpy2 directly into the library - but not rpy2-arrow, due to its newness and lack of user base. So having Arrow support built directly into rpy2, rather than as an external library, would determine whether rpy2 could be integrated with polars - and hopefully gain a number of new users as a result!

**Comment by krassowski** [comment]
That's sound interesting! I also thought that a closer integration with arrow might be worth a shot given pandas moving in that direction.

Do you have a link to relevant discussions about the polars integration?

**Comment by Wainberg** [comment]
This was from a one-on-one discussion with @stinodego, one of the 4 core developers of polars. He says "I like the idea" of adding R integration and that if Arrow support were added directly to rpy2 rather than being in rpy2-arrow as a separate library, "That would definitely help build a stronger case for this!"

Yes, it would definitely help with pandas support as well! From looking through past Github issues, I can see @lgautier has recommended folks use rpy2-arrow for speed on multiple occasions.

If Laurent is interested in adding Arrow support directly into rpy2, I will follow up with the polars folks by making a Github issue about adding rpy2 support to polars.

**Comment by Wainberg** [comment]
I think we were contemplating something like `pl.DataFrame({'a': [1, 2, 3]}).to_r()` and `pl.DataFrame.from_r(r_dataframe)`. The implementation would entirely be on the polars side, you wouldn't have to implement anything extra.

To quote @stinodego (the polars developer), "I like the idea [of supporting interfacing with R] but we're not adding support for a package that is on 0.0.8 and has almost no users". I think he would see integrating the package into rpy2 itself as a signal that you are committed to the maintenance burden of supporting Arrow.

**Comment by lgautier** [comment]
Thanks for sharing the additional thoughts.

(...)
> To quote @stinodego (the polars developer), "I like the idea [of supporting interfacing with R] but we're not adding support for a package that is on 0.0.8 and has almost no users". I think he would see integrating the package into rpy2 itself as a signal that you are committed to the maintenance burden of supporting Arrow.

The concern is legitimate but I am less sure about the signal watched here.

`rpy2-arrow` started as an attempt to build a proof of concept when Arrow was taking off.
Rpy2 has limited support for in-process sharing of arrays using Python/Numpy buffer protocol
but Arrow had the potential to be a good general solution for that. The Arrow devs have been
really helpful (e.g., https://issues.apache.org/jira/browse/ARROW-11120) and `rpy2-arrow` has been on the forefront of working out interoperability issues (e.g., https://github.com/apache/arrow/pull/35812). You'll also find Arrow core developers commenting in Section Issues of the rpy2-arrow project. In that respect, yes there has been demonstrated commitment to get Arrow supported.

I do not plan to integrate `rpy2-arrow` in `rpy2` right now. I am already considering splitting feature sets with optional dependencies (numpy, pandas, ipython/jupyter, wrappers for R packages ggplor2, dplyr, tidyr) into their own coherent sets of rpy2 extensions. Presence in rpy2 is therefore not a specific indicator of commitment for support for the said dependencies. On the contrary, this is opens up the possibility to distribute maintenance if there is a chance to do so (if you think you'd like to be an additional dev or maintainer, do reach out). It would also help decouple conversion rules (here a Python user using polars instead of pandas would be unencumbered by pandas if not used). Here it would be conversion rules set for polars, similarly to what is done for `pandas` in `rpy2.robjects.pandasri`.

Having that said, this is touching on the broader question of maintenance that this is an inherent challenge for Open Source. In addition to that, if what is used tend to be maintained and being used depends of being maintained we have a circular dependency. Or may be a self-fulfilling prophecy that is up to us to make.

**Comment by Wainberg** [comment]
It would probably be less confusing to just have one package, and support numpy, pandas, arrow, ipython/jupyter, ggplot2, dplyr, tidyr etc. as optional dependencies. If you tried to use those parts of the package without having the optional dependency installed, you would get a runtime error. Polars does this already with all of their optional dependencies, and it works quite nicely in practice.

You could also consider getting rid of the wrappers for R packages entirely (ggplot2, dplyr, tidyr) to reduce maintenance burden - I'd personally never heard of them and I've used rpy2 extensively.

**Comment by stinodego** [comment]
Users can already do the conversion from Polars to R using `polars` and `rpy2`/`rpy2-arrow`. So there is no real _need_ to add any further integrations.

They could be nice to have. But we are not sure about supporting the additional maintenance burden, and it seems that the same is true for the side of `r2py`. So let's close this issue for now.

**Comment by lgautier** [comment]
Sounds good.

I am yet to play a bit with `polars`. If achieving things is only few lines of code using `rpy2-arrow` what be done is to add those in documentation (and ideally place the code examples behind automated testing in a doc building pipeline). If the integration with `polars` turns out to require a bit more than that and, say, a set of `rpy2` conversion rules (possibly using themselves the current content in `rpy2-arrow`) that code could in a `rpy2-polars` package until the size of user base or stakes are high enough to have that code integrated elsewhere. I might have the time to look at it over the end-of-year break.

**Comment by lgautier** [comment]
FYI - Candidate addition to `rpy2-arrow`:  conversion rules for `polars`. After thinking about it could make sense to have that in `rpy2-arrow` rather than in a standalone package `rpy2-polars`: https://github.com/rpy2/rpy2-arrow/pull/14
