### ISSUE TITLE
kernel is falling while running r_to_py from reticulate package

### ISSUE THREAD

**Issue by MaximumV** [rpy2/rpy2#725]
Hi to all!
Pls advice if this is possible to run any reticulate commands in the rpy2 and what should I do to configure?
I installed the reticulate 
`import rpy2.interactive as r_pack
import rpy2.interactive.packages # this can take few seconds
rlib = r_pack.packages.packages
r_pack.packages.importr("utils")
package_name = "reticulate"
rlib.utils.install_packages(package_name)
`
but trying to run r_to_py under %%R showes kernel falling

**Comment by krassowski** [comment]
What are you trying to achieve using reticulate in rpy2? It should not be needed for most use cases. In particular, you can export objects with

```R
%%R -o obj
obj = c(1, 2, 3)
```

**Comment by lgautier** [comment]
Unfortunately there is still an issue when trying to get reticulate and rpy2 working together. Last I checked this was due to the embedded R being initialized twice. R is quite brittle when doing so, and a segfault is the immediate outcome in my experience.

Hopefully I'll find the time to look at it again for a future rpy2 release.
