### ISSUE TITLE
Free memory from R session in python

### ISSUE THREAD

**Issue by LuckyMD** [rpy2/rpy2#730]
**Is your feature request related to a problem? Please describe.**
I have a quick question about rpy2 that you might be able to answer. I'm running a normalization function in `R` in a function via `rpy2` at the moment and there's a memory leak as the `R` kernel uses memory even after I exit the function. I'm already removing all saved objects in that kernel, but there are still loaded libraries ofc. 

**Describe the solution you'd like**
Is it possible to close the `R` kernel running the background without closing the python kernel? I hear that running ro.r('q()') also quits the python kernel.

**Describe alternatives you've considered**
I could of course check if I can just detach the loaded modules and see if that frees up memory, but there would still be a memory overhead from the runnin kernel.

This is related to a bug reported here: https://github.com/theislab/scib/issues/155

**Comment by lgautier** [comment]
The memory leak can come from:
- the R package you are using (in which case the leak is probably originating from a C extension to that package)
- `rpy2`. There is always the possibility that something was overlooked. In that case this is a bug.
- circular references requiring a nudge to be freed. In Python this means calling the garbage collector.

I can see from the comments in the the reference issue you are providing that calling the garbage collector has been attempted without notable success. and that unloading the associated R package only provides a partial relief.

If you want to end the embedded R you should not call R's `q()` (because by default it will terminate whatever process it is running in, which is your Python process). The function `endr` should be used instead: https://rpy2.github.io/doc/v3.3.x/html/rinterface.html#rpy2.rinterface.endr However, this is irreversible and R cannot be initialized again from the same process. There is no guarantee it will free the memory either.

Whenever needing to have disposable embedded R processes, you will have to use subprocesses (for example using the Python module `subprocess`).

**Comment by lgautier** [comment]
I am understanding this is currently not believed to be a bug with `rpy2`. Reopen if I am mistaken.

**Comment by LuckyMD** [comment]
Hi @lgautier,

This was very helpful, thank you! Indeed, I do not expect this to be a bug in rpy2. As I am using `rpy2` just in a function to execute a single command in `R`, I think `rpy2.rinterface.endr()` should be exactly what I am looking for. 

I guess the next time I run the same function again, it should just reload `rpy2` and therefore start a new R kernel in the background anyway, no?
