### ISSUE TITLE
AttributeError: 'RS4' object has no attribute 'new'

### ISSUE THREAD

**Issue by nalomran** [rpy2/rpy2#731]
I am using rpy2 v.3.3.5 to trying to mimic the following R code from the R package "MatrixEQTL" within Python:

```
# in R
library(MatrixEQTL)
data <- SlicedData$new()
```

which runs just fine, but when I tried to mimic the above in python:
```
# in python
from rpy2.robjects.packages import importr
mqtl = importr('MatrixEQTL')
snv = mqtl.SlicedData().new()
```

I get the following error:
`AttributeError: 'RS4' object has no attribute 'new'`

The type of SlicedData is R object that contains the SlicedData class:

```
>>>mqtl.SlicedData()
R object with classes: ('SlicedData',) mapped to:

>>>dir(mqtl.SlicedData())
['_RObjectMixin__close', '_RObjectMixin__fifo', '_RObjectMixin__file', '_RObjectMixin__readlines', '_RObjectMixin__show', '_RObjectMixin__sink', '_RObjectMixin__slots', '_RObjectMixin__tempfile', '_RObjectMixin__unlink', '__abstractmethods__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rname__', '__setattr__', '__setstate__', '__sexp__', '__sexp_refcount__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', '_sexpobject', 'do_slot', 'do_slot_assign', 'extends', 'get_attrib', 'isclass', 'list_attrs', 'named', 'names', 'names_from_c_attribute', 'r_repr', 'rclass', 'rid', 'rsame', 'slotnames', 'slots', 'typeof', 'validobject']
```
How would I be able to access the `"new()"` method above with mqtl.SlicedData() R object within python?

**Comment by lgautier** [comment]
This seems to be usage question rather than a issue. The documentation covers a bit R S4 objects:
https://rpy2.github.io/doc/v3.3.x/html/robjects_oop.html#s4-objects

If this is an S4 Reference Class the doc is a bit lacking, but there is this discussion: https://stackoverflow.com/questions/63069677/how-to-execute-s4-class-method-in-python-using-rpy2

If you define a Python class to mirror the R class, for example
```python
class SlicedData(RS4):
    def new(self, <args>, <kwargs>):
        pass
        # Call the S4 method "new"
```
and you wish to customize the rpy2 conversion the documentation is here:
https://rpy2.github.io/doc/v3.3.x/html/robjects_convert.html#customizing-the-conversion

**Comment by lgautier** [comment]
I closed it as it does not seem to be an issue with rpy2 itself. Reopen if I am mistaken.
