### ISSUE TITLE
Wrong R binary is selected when RPY2_CFFI_MODE=API

### ISSUE THREAD

**Issue by matthewwardrop** [rpy2/rpy2#772]
**Describe the issue or bug**

When multiple versions of R are installed on the machine, when in "API" CFFI mode rpy2 selects the wrong version of R.

For example, on my system, I have two versions of R:

 - /home/.../conda/bin/R (version 3.6.3)
 - /usr/bin/R (version 4.0.3)

When I have activated the conda environment, the first (older) version of R is first on the path, but by default (when RPY2_CFFI_MODE="API") the system version of R is selected instead.

**To Reproduce**

The following commands were run from within the conda virtual environment:

> RPY2_CFFI_MODE=ABI python -c "import rpy2.robjects as r; print(r.r('R.version[\"version.string\"]')[0][0])"
R version 3.6.3 (2020-02-29)

> `RPY2_CFFI_MODE=API python -c "import rpy2.robjects as r; print(r.r('R.version[\"version.string\"]')[0][0])"`
R version 4.0.3 (2020-10-10)

Uninstalling the system version of R resolved the issue, and reinstalling it caused the failure mode seen above again.

**Expected behavior**

Both CFFI modes should interact with the correct environment.

**Comment by lgautier** [comment]
I have a system R (3.6.3 available through the distro) and a manually-managed R (compiled from source). I set the PATH and LD_LIBRARY_PATH to use the later. I cannot reproduce the issue.

```
$ RPY2_CFFI_MODE=ABI python -c "import rpy2.robjects as r; print(r.r('R.version$version.string')[0])"
R version 4.0.3 Patched (2020-11-06 r79405)
$ RPY2_CFFI_MODE=API python -c "import rpy2.robjects as r; print(r.r('R.version$version.string')[0])"
R version 4.0.3 Patched (2020-11-06 r79405)
```

Do you know if conda changes `LD_LIBRARY_PATH`?

**Comment by matthewwardrop** [comment]
Aha, it does not. Instead it expects binaries to set the RPATH flag, which is normally handled by the conda build process. Something about the way rpy2 is compiled in the [conda-forge feedstock](https://github.com/conda-forge/rpy2-feedstock), must not be right.

Looking at the generated binary, I see:
> readelf -d _rinterface_cffi_api.abi3.so |head -20

Dynamic section at offset 0x1b860 contains 22 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libR.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000f (RPATH)              Library rpath: [$ORIGIN/../..]
 ....

But the R libraries are split out into the $R_HOME folder, in this case `$ORIGIN/../../R/lib`.

In this case, however, it is unclear to me how it works when I uninstall my system R. Is there some fallback LD lookup path?

**Comment by matthewwardrop** [comment]
In any case, I patched the conda-forge recipe in conda and was able to generate a binary that worked nicely! Thanks @lgautier !

**Comment by lgautier** [comment]
I don't know much about how the conda package is built. The only thing I know is that a broken conda package for rpy2 is regularly at the root of reported issues.

On the rpy2 side, nothing particularly clever is done with linking. At build time it will fetch compiling flags from whatever R is found first in the PATH and passes that to the cffi builder(s) (one for for ABI mode, one for API mode). Now that you are asking I do not know whether cffi will make those paths implicitly picked up at load time. I am using `LD_LIBRARY_PATH` on my dev machine, but I am not trying what happens when installing with one version of R and loading with an other one. It used to work when rpy2 was a C-extension but I have not tried again since the move to cffi.

What is picked up by rpy2 (linking flags) can be checked by running:
```bash
python -m rpy2.situation
```

To set the `LD_LIBRARY_PATH` one can do:

```bash
export LD_LIBRARY_PATH=$(python -m rpy2.situation LD_LIBRARY_PATH):"${LD_LIBRARY_PATH}"
```

**Comment by matthewwardrop** [comment]
Thanks again. My patch downstream in conda-forge fixes the RPATH.  https://github.com/conda-forge/rpy2-feedstock/pull/77. I'll test it in MacOS too.

Whenever I've come across rpy2 issues in conda I try to fix them rather than work around them :).
