### ISSUE TITLE
Passing Python Objects which inherit from RS4 class to R Functions and Preserving Attributes

### ISSUE THREAD

**Issue by anibo12** [rpy2/rpy2#783]
I am working on a package migration project from R to Python and I start with writing python wrappers classes which inherit from some RS4 classes. I need to pass those wrapper objects to both Python and R functions. However, when I pass the wrapper objects to R functions, it only passes the R object which is embedded inside the python objects. Therefore, inside the R functions, it calls those methods from R object instead of through the wrapper objects. Is it possible to preserve the python attributes and pass the whole python object to the R function which is similar to use reticulate package to import python module and then initialize?

```
import rpy2.robjects as robjects
import rpy2.rinterface as rinterface

import rpy2.robjects.conversion as conversion
from rpy2.robjects.conversion import localconverter
from rpy2.robjects import default_converter
class ShockGenTest(robjects.methods.RS4):
    def __init__(self):
        self.x = 1
        r_obj = robjects.r['source']("/repos/ShockGenerator/macroclasses/rZero.R")
        r_obj = robjects.r['rZero']()
        super().__init__(r_obj)

py_obj = ShockGenTest()
robjects.r["class"](py_obj)
```

Output : 
> <rpy2.robjects.vectors.StrVector object at 0x7fe5c4958908> [RTYPES.STRSXP]
> R classes: ('character',)
> ['rZero']

The goal is to have the following kind of object inside R function:
> library(reticulate)
> py_c <- import("ShockGenTest")

> py_obj = py_c$ShockGenTest()
> class(py_obj)
[1] "ShockGenTest.ShockGenTest"                        
[2] "rpy2.robjects.methods.RS4"                        
[3] "rpy2.robjects.robject.RObjectMixin"               
[4] "rpy2.rinterface.SexpS4"                           
[5] "rpy2.rinterface_lib.sexp.Sexp"                    
[6] "rpy2.rinterface_lib._rinterface_capi.SupportsSEXP"
[7] "python.builtin.object"

**Comment by lgautier** [comment]
This seems more like a question specific to an intent for your code than an issue or wish for an improvement in `rpy2`. StackOverflow is a better place to ask (see section Questions and Issue here: https://rpy2.github.io/).

What you have in your example is that an S4 class "rZero" is defined in your R script. The Python class you are declaring will wrap it on the Python side, and it is up to the code author on the Python side to decide how it is wrapped.

Should you access an instance of that class from `reticulate`, it would just look like how `reticulate` wraps Python objects. The only problem you may have at the moment is that `reticulate` is causing a segfault when initializing from an R embedded in a Python process (I believe that the issue is with `reticulate`).

Otherwise the following in your example is behaving just like it is intended to:
```python
py_obj = ShockGenTest()
robjects.r["class"](py_obj)
```

`py_obj` is an R S4 object wrapped by a Python class, but when passed to an R function it is just that R object.
