### ISSUE TITLE
rpy2 errors when loading curl.so inside conda environment for 3.9.4

### ISSUE THREAD

**Issue by thistleknot** [rpy2/rpy2#801]
**Describe the issue or bug**

Oracle Linux 8.3
Python 3.9.4 (using miniconda)
R 4.0.5 (built)
./configure --prefix=/mnt/distvol/R/4.0.5 '--with-cairo' \
'--with-jpeglib' '--with-readline' '--with-tcltk' \
'--with-blas' '--with-lapack' '--enable-R-profiling' \
'--enable-R-shlib' \
'--enable-memory-profiling'

make
make install

**To Reproduce**

conda create -n py39 python=3.9
conda activate py39
LD_PRELOAD=/mnt/distvol/R/4.0.5/lib64/R/library/curl/libs/curl.so python3

**Expected behavior**
inside R curl.so is used by various libraries including forecast.  I get various errors related to shared objects when attempting to load this library.  I have shortened the issue to the direct shared object that will not load.

**Error**
python3: symbol lookup error: /lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b

**Additional context**
I am able to load forecast just fine from within R directly, but am unable to load it within python 3.9.4 due to an error with some package being built with openssl 1.1.1b

I understand this might be an environment issue.  I'm looking for workarounds if any.
I can dyn.load('/mnt/distvol/R/4.0.5/lib64/R/library/curl/libs/curl.so') the shared object just fine inside R

**Comment by lgautier** [comment]
Historically conda has been the source of quite a few issues reports for rpy2. I am otherwise not using it much myself.
Setting `LD_PRELOAD` as you do will not necessarily resolve properly the dynamic loading of dependencies. Here your Python process seems to have already loaded openssl by the time R's curl needs it.

I am unsure this is an rpy2 issue. May be someone on StackOverflow can answer the question though.

In the meantime I am closing this. Reopen if I am mistaken and this is an rpy2 issue.
