### ISSUE TITLE
Warn if pandas data frame has duplicate values in index when converting to R data frame

### ISSUE THREAD

**Issue by krassowski** [rpy2/rpy2#811]
**Is your feature request related to a problem? Please describe.**
Conversion from pandas DataFrame to R data.frame works as expected, but when there are duplicate values in pandas Data frame index the rownames in R data frame get lost. This is fine, but it took me quite a while to figure out the reason for missing row names after conversion.

<details>

```python
%load_ext rpy2.ipython
from pandas import Series
```

</details>

This works well:

```python
df = Series([1, 2], index=['a', 'b']).to_frame()
df
```

> |    |   0 |
> |:---|----:|
> | a  |   1 |
> | b  |   2 |

```python
%%R -i df
df
```

>   0
> a 1
> b 2

This leads to loss of row names without warning the user:

```python
df_dup = Series([1, 2], index=['a', 'a']).to_frame()
df_dup
```

> |    |   0 |
> |:---|----:|
> | a  |   1 |
> | a  |   2 |

```python
%%R -i df_dup
df_dup
```

>   0
> 1 1
> 2 2

**Describe the solution you'd like**
I would like a warning to be emitted when converter detects a data frame with duplicated entries in index which could result in loss of data.

**Describe alternatives you've considered**
- I would **not** want to have it raise an error. There are multiple cases when index is of no interest or duplicate indices are intended.
- It could be possible to preserve the duplicated values by calling `reset_index()` prior to conversion, but I think this should be a decision that the user makes based on the warning rather than a built-in behaviour of the converter.

**Additional context**

- rpy2 3.4.5
- R 4.0.4
- pandas 1.2.4

**Comment by lgautier** [comment]
Thanks for the report.

Whether to silently drop what causes the issue, issue a warning, or raise an exception is Cornelian dilemma in a few places in rpy2. Historically I have favored raising errors: `rpy2` was initially designed to help with the implementation of applications that leverage R for specific features. Because of that raising an error early (and let the developer decide how to handle it) seemed the best way. I am reading that an error would not make you happy thought.

May be there is a way to find an hybrid between errors and warnings through a custom warning (subclass) if Python has a way to optionally promote specific warnings to errors. Developers of application could toggle that if they wish.

**Comment by krassowski** [comment]
I think that Python can be run with `-W error:::rpy2[.*]` option to convert all rpy2 warnings to errors (as described in https://docs.python.org/3/library/warnings.html#describing-warning-filters).

Indeed for certain use-cases/development flows errors are a better fit, while for interactive data exploration they are more of an annoyance. An additional argument for using a warning is to maintain backward compatibility with earlier versions (currently duplicate indices are silently ignored).
