### ISSUE TITLE
rpy2 cant find broom tidy

### ISSUE THREAD

**Issue by timpiperseek** [rpy2/rpy2#830]
I am sure that I am probably doing something wrong but for the life of me, I cannot figure out what it is?

I am trying to reproduce this [example](https://cran.r-project.org/web/packages/broom/vignettes/broom.html)
This works in R
`
library(broom)
lmfit <- lm(mpg ~ wt, mtcars)
tidy(lmfit)
`

and I am trying to reproduce the above into python code.

```
from rpy2.robjects.packages import importr, data
from rpy2.robjects import Formula
datasets = importr('datasets')
stats = importr('stats')
broom = importr('broom')

mtcars_env = data(datasets).fetch('mtcars')
mtcars = mtcars_env['mtcars']

fmla = Formula('mpg ~ wt')
lmfit = stats.lm(fmla, mtcars)
broom.tidy(lmfit)
```

The error message that I am getting is the following 
`module 'broom' has no attribute 'tidy'`

any help would be really appreciated

**Comment by krassowski** [comment]
This is because the `broom` package does not provide the `tidy` generic. In R (differently to Python) a common pattern is to use so-called _method dispatch_, this is implementing multiple methods (functions) which perform conceptually the same action, but accept different kind of input and then having a single _generic_ (or _dispatcher_) function on top of that which decides which implementation method to use (depending on the type of provided arguments). `broom` provides specific methods, but does not provide the _generic_ function to dispatch those. You can verify that by looking at the list of methods it provides:

![Screenshot from 2021-11-15 17-10-43](https://user-images.githubusercontent.com/5832902/141824492-27e07026-aa06-411d-bb75-ffec0f54402c.png)

or by clicking on the link to [`tidy()`](https://generics.r-lib.org/reference/tidy.html) in the [`broom` documentation]((https://broom.tidymodels.org/)) which leads to an external website of `generics` package. So what you want to do is to import the generics:

```python
generics = importr('generics')
tidy = generics.tidy
tidy(lmfit)
```

which should work well.

One could ponder if rpy2 should automagically add methods from third-party packages which are attached by R when loading a library. I don't know - but I think that there are cases where that could lead to namespace conflicts (which are unfortunately common in the messy model of R import system). Maybe there should be a separate function for that, which would mirror the R's `library()` behaviour more closely?

**Comment by timpiperseek** [comment]
That makes sense, thankyou

**Comment by lgautier** [comment]
> One could ponder if rpy2 should automagically add methods from third-party packages which are attached by R when loading a library. I don't know - but I think that there are cases where that could lead to namespace conflicts (which are unfortunately common in the messy model of R import system).

Yes, this is would nice. But from what I have learned the hard way that with R and its packages, there will be issues such as the one you describe. rpy2 is trying to make R packages as if they were Python modules with `importr`, but this might just be one of the limits.

> Maybe there should be a separate function for that, which would mirror the R's library() behavior more closely?

The R function "library" only has side effects. It does not return much; it loads the R package, and attaches the package's namespace to the R search path. The Python class returned by `importr` has an attribute `_env` that binds to an R "environment" for the R package. Naturally this is wrapped by an rpy2 object for R environment. The method `find` can be used (it will look an R symbol, starting from the environment):

```python
broom._env.find('tidy')
```
One can note that the name conflict problem exists here as well. If an R package has a symbol `.env` or `_env` this won't work.

A similar result can be achieved with:

```python
from rpy2.robjects.packages import wherefrom
wherefrom('tidy', startenv=broom._env)
```
