### ISSUE TITLE
Would this work for a R script with external libraries?

### ISSUE THREAD

**Issue by gabrielpulga** [rpy2/rpy2#862]
Sorry if this has been asked here before. I'm working with several R scripts that possess a range of external libraries :
```
library(officer)
library(dplyr)
library(tidyr)
library(DatastreamDSWS2R)
library(ggrepel)
library(lubridate)
library(magrittr)
library(data.table)
library(zoo)
library(rvg)
library(aws.s3)
```
I'm looking for something that turns my R code into python code - or lets me execute the R code through Python.

The reason? AWS doesn't support native R in Lambda, and running scripts with a runtime layer proved to be a hurdle.

Would rpy2 help me solve this issue? I'm a bit worried it only supports the libraries and dependencies that come within R.

**Comment by lgautier** [comment]
This kind of question is not so much about an issue or a feature request for `rpy2`. You will get more people reading the question on StackOverflow for example.

Otherwise `rpy2` will let you run any R code. If you need specific R libraries they must be installed / available. Doing that for each Lambda call does not seem like a good option, but that the same for Python libraries and/or third-party libraries or tools needed to run the Lambda. There exists strategies for the latter, and they can be applied to R packages.
