### ISSUE TITLE
ts R object is returned as a numpy array & frequency is lost

### ISSUE THREAD

**Issue by ltsaprounis** [rpy2/rpy2#949]
**Describe the issue or bug**
Time series objects are converted to numpy ndarrays and the frequency argument is lost.
This causes issues with using this object in other libs e.g. the R forecast package

**To Reproduce**
```python
import numpy as np

import rpy2.robjects as robjects
from rpy2.robjects.packages import importr
from rpy2.robjects import pandas2ri

pandas2ri.activate()
stats_package = importr('stats')

python_values = np.arange(24)

r_values = robjects.FloatVector(python_values)
start = robjects.IntVector([2020, 1])
r_times_series_data = stats_package.ts(r_values, start=start, frequency=12)

print(type(r_times_series_data))
# returns: <class 'numpy.ndarray'>
```

**Expected behavior**
I don't know much about rpy2 to recommend an exact solution, but, I believe that the returned object should be a ts like object and not a numpy array.

**Comment by lgautier** [comment]
The use of a local converter is recommended over the use of `panda2ri.activate` (see https://rpy2.github.io/doc/latest/html/pandas.html#interoperability-with-pandas).

Otherwise, R's C level time-series objects are numerical (double) arrays wrapped in an R class that modifies it behavior. Deciding which R arrays should **not** be converted to numpy arrays while the numpy conversion rules are active (as they implicitly set with pandas conversion rules) has to be made per R class. Currently there no special rule for R objects of class `ts`. May be there should be one shipping with `rpy2` since `ts` is part of R's standard library, but unless a mapping to a Python class can be worked out this would return an R `rpy2.robjects.FloatVector`. Using a localconverter only when conversion from an to `pandas` is needed will achieve that.

**Comment by ltsaprounis** [comment]
Thanks for the super quick response @lgautier!
Yes you're right! If I don't use `pandas2ri` it all works fine.

```python
import numpy as np

import rpy2.robjects as robjects
from rpy2.robjects.packages import importr
stats_package = importr('stats')

python_values = np.arange(24)

r_values = robjects.FloatVector(python_values)
start = robjects.IntVector([2020, 1])
r_times_series_data = stats_package.ts(r_values, start=start, frequency=12)

print(type(r_times_series_data))
# returns: <class 'rpy2.robjects.vectors.FloatVector'>

print(r_times_series_data)
# returns:
# Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
# 2020   0   1   2   3   4   5   6   7   8   9  10  11
# 2021  12  13  14  15  16  17  18  19  20  21  22  23
```
